import { DatabaseState, Product, User, Coupon, SubscriptionBox } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'USR-CUST-1',
    name: 'Akash K. Shankar',
    email: 'akash.shankar@gmail.com',
    phone: '+91 98470 12345',
    role: 'Customer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    region: 'Kozhikode',
    address: 'Flat 4B, Malabar Heights, Beach Road, Kozhikode, Kerala - 673001',
    loyaltyPoints: 350,
    walletBalance: 1250,
  },
  {
    id: 'USR-FARM-1',
    name: 'Ramesh Kumar (Green Canopy Farms)',
    email: 'ramesh.organic@farm.in',
    phone: '+91 94471 88990',
    role: 'Farmer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    region: 'Wayanad',
    organicVerified: true,
  },
  {
    id: 'USR-FARM-2',
    name: 'Lakshmi Amma (Bio Valley Organic)',
    email: 'lakshmi.valley@farm.in',
    phone: '+91 94952 33445',
    role: 'Farmer',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    region: 'Palakkad',
    organicVerified: true,
  },
  {
    id: 'USR-HOME-1',
    name: 'Ananya Nair (Terrace Green Garden)',
    email: 'ananya.homegarden@gmail.com',
    phone: '+91 98950 55667',
    role: 'Home Garden Seller',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    region: 'Kozhikode',
    organicVerified: true,
  },
  {
    id: 'USR-OUTLET-1',
    name: 'Kozhikode Central Community Outlet',
    email: 'manager.clt@organicconnect.in',
    phone: '+91 495 2728990',
    role: 'Outlet Manager',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    region: 'Kozhikode',
  },
  {
    id: 'USR-DELIV-1',
    name: 'Rajesh V. (Eco Delivery Express)',
    email: 'rajesh.delivery@organicconnect.in',
    phone: '+91 97455 66778',
    role: 'Delivery Partner',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    region: 'Kozhikode',
  },
  {
    id: 'USR-ADMIN-1',
    name: 'Dr. S. Radhakrishnan (Admin)',
    email: 'admin@organicconnect.in',
    phone: '+91 98460 99999',
    role: 'Admin',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    region: 'Kerala HQ',
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  { code: 'ORGANIC20', discountType: 'PERCENT', value: 20, minOrderAmount: 300, description: '20% off on orders above ₹300' },
  { code: 'FRESH50', discountType: 'FLAT', value: 50, minOrderAmount: 250, description: 'Flat ₹50 off on fresh harvest' },
  { code: 'WELCOME100', discountType: 'FLAT', value: 100, minOrderAmount: 500, description: '₹100 off on first major order' },
];

export const INITIAL_SUBSCRIPTION_BOXES: SubscriptionBox[] = [
  {
    id: 'SUB-1',
    name: 'Essential Family Vegetable Basket',
    servesPeople: '3 - 4 Persons',
    estimatedWeightKg: 7.5,
    pricePerWeek: 499,
    itemsIncluded: ['Organic Tomatoes (1kg)', 'Potatoes (1kg)', 'Onions (1kg)', 'Green Chillies (100g)', 'Palak Greens (1 bunch)', 'Ladies Finger (500g)', 'Bitter Gourd (500g)'],
    isPopular: true,
    description: 'A curated weekly mix of 8-10 essential daily vegetables fresh from Wayanad farms.',
    frequency: 'Weekly',
    itemsCount: '7 - 8 kg',
    pricePerDeliver: 499,
    image: 'https://images.unsplash.com/photo-1610348725531-843dff563e2c?w=500&auto=format&fit=crop&q=80',
    popular: true,
    contents: ['Organic Tomatoes (1kg)', 'Potatoes (1kg)', 'Onions (1kg)', 'Green Chillies (100g)', 'Palak Greens (1 bunch)', 'Ladies Finger (500g)', 'Bitter Gourd (500g)'],
  },
  {
    id: 'SUB-2',
    name: 'Exotic Organic Greens & Herbs Box',
    servesPeople: '2 Persons',
    estimatedWeightKg: 2.5,
    pricePerWeek: 299,
    itemsIncluded: ['Organic Palak', 'Amaranthus Greens', 'Fresh Coriander', 'Mint Leaves', 'Curry Leaves', 'Lemon Grass'],
    isPopular: false,
    description: 'Fresh pesticide-free leafy greens, microgreens, and aromatic cooking herbs harvested daily.',
    frequency: 'Bi-Weekly',
    itemsCount: '4 - 5 Bunches',
    pricePerDeliver: 299,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500&auto=format&fit=crop&q=80',
    contents: ['Organic Palak', 'Amaranthus Greens', 'Fresh Coriander', 'Mint Leaves', 'Curry Leaves', 'Lemon Grass'],
  },
  {
    id: 'SUB-3',
    name: 'Home Garden Special Micro-Basket',
    servesPeople: '2 - 3 Persons',
    estimatedWeightKg: 3.5,
    pricePerWeek: 349,
    itemsIncluded: ['Terrace Native Tomatoes', 'Organic Yardlong Beans', 'Bird Eye Chillies', 'Curry Leaves', 'Homegrown Ridge Gourd'],
    isPopular: false,
    description: 'Limited edition heirloom vegetables harvested directly from urban home terrace gardens.',
    frequency: 'Weekly',
    itemsCount: '3 - 4 kg',
    pricePerDeliver: 349,
    image: 'https://images.unsplash.com/photo-1595855759920-86582396756a?w=500&auto=format&fit=crop&q=80',
    contents: ['Terrace Native Tomatoes', 'Organic Yardlong Beans', 'Bird Eye Chillies', 'Curry Leaves', 'Homegrown Ridge Gourd'],
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'PROD-101',
    name: 'Organic Country Tomatoes (Thakkali)',
    hindiName: 'Tamatar',
    category: 'Root Vegetables',
    price: 48,
    unit: '1 kg',
    quantity: 65,
    seller: 'Ramesh Kumar (Green Canopy Farms)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-1',
    region: 'Wayanad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 34,
    harvestTime: 'Harvested Today at 5:30 AM',
    description: 'Naturally ripened heirloom country tomatoes grown with vermicompost in Wayanad hills. Rich juicy flavor perfect for curries.',
    isPopular: true,
  },
  {
    id: 'PROD-102',
    name: 'Fresh Organic Palak Spinach (Cheera)',
    hindiName: 'Palak',
    category: 'Leafy Greens',
    price: 32,
    unit: '1 Bunch (300g)',
    quantity: 40,
    seller: 'Ananya Nair (Terrace Green Garden)',
    sellerRole: 'Home Garden Seller',
    sellerId: 'USR-HOME-1',
    region: 'Kozhikode',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 22,
    harvestTime: 'Harvested Today at 6:00 AM',
    description: 'Tender home-grown spinach leaves rich in iron and minerals. Zero chemical sprays or insecticides used.',
    isPopular: true,
  },
  {
    id: 'PROD-103',
    name: 'Hill-Grown Bitter Gourd (Pavakka)',
    hindiName: 'Karela',
    category: 'Gourds & Squashes',
    price: 55,
    unit: '500 g',
    quantity: 30,
    seller: 'Ramesh Kumar (Green Canopy Farms)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-1',
    region: 'Wayanad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=500&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewsCount: 18,
    harvestTime: 'Harvested Yesterday Evening',
    description: 'Crisp green organic bitter gourds excellent for diabetic management and traditional Kerala stir fries.',
  },
  {
    id: 'PROD-104',
    name: 'Native Ladies Finger (Vendakka / Okra)',
    hindiName: 'Bhindi',
    category: 'Pods & Beans',
    price: 42,
    unit: '500 g',
    quantity: 50,
    seller: 'Lakshmi Amma (Bio Valley Organic)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-2',
    region: 'Palakkad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1628773822503-930a8581898e?w=500&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewsCount: 29,
    harvestTime: 'Harvested Today at 6:15 AM',
    description: 'Tender green Okra harvested early morning. Snap off tips effortlessly indicating peak freshness.',
    isPopular: true,
  },
  {
    id: 'PROD-105',
    name: 'Organic Small Shallots (Cheriya Ulli)',
    hindiName: 'Chota Pyaz',
    category: 'Root Vegetables',
    price: 75,
    unit: '500 g',
    quantity: 80,
    seller: 'Lakshmi Amma (Bio Valley Organic)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-2',
    region: 'Palakkad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cf?w=500&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 45,
    harvestTime: 'Sun-dried 2 Days Ago',
    description: 'Traditional aromatic small onions cultivated naturally in Palakkad black soil. Essential for South Indian sambar.',
    isPopular: true,
  },
  {
    id: 'PROD-106',
    name: 'Fresh Curry Leaves (Karyappila)',
    hindiName: 'Kadi Patta',
    category: 'Spices & Herbs',
    price: 15,
    unit: '1 Bunch (100g)',
    quantity: 100,
    seller: 'Ananya Nair (Terrace Green Garden)',
    sellerRole: 'Home Garden Seller',
    sellerId: 'USR-HOME-1',
    region: 'Kozhikode',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1626200419199-391ae487d14a?w=500&auto=format&fit=crop&q=80',
    rating: 5.0,
    reviewsCount: 56,
    harvestTime: 'Harvested Just 2 Hours Ago',
    description: 'Extremely fragrant dark green terrace curry leaves. Adds natural aroma to tadka and curries.',
  },
  {
    id: 'PROD-107',
    name: 'Organic Drumsticks (Muringakka)',
    hindiName: 'Sahjan',
    category: 'Pods & Beans',
    price: 38,
    unit: '250 g (approx 3 sticks)',
    quantity: 35,
    seller: 'Ramesh Kumar (Green Canopy Farms)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-1',
    region: 'Wayanad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1598170845058-12ef4a4575c1?w=500&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewsCount: 14,
    harvestTime: 'Harvested Today Morning',
    description: 'Long fleshy organic drumsticks rich in nutrients and antioxidants. Perfect for Avial and Sambar.',
  },
  {
    id: 'PROD-108',
    name: 'Farm Fresh Green Chillies (Pachamulaku)',
    hindiName: 'Hari Mirch',
    category: 'Spices & Herbs',
    price: 25,
    unit: '250 g',
    quantity: 45,
    seller: 'Ananya Nair (Terrace Green Garden)',
    sellerRole: 'Home Garden Seller',
    sellerId: 'USR-HOME-1',
    region: 'Kozhikode',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1588880331179-bc9b93a8cb5e?w=500&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 31,
    harvestTime: 'Harvested Today at 7:00 AM',
    description: 'Spicy organic green chillies harvested from healthy terrace potted plants.',
  },
  {
    id: 'PROD-109',
    name: 'Wayanad Organic Ginger (Inchi)',
    hindiName: 'Adrak',
    category: 'Spices & Herbs',
    price: 60,
    unit: '250 g',
    quantity: 40,
    seller: 'Ramesh Kumar (Green Canopy Farms)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-1',
    region: 'Wayanad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=500&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 28,
    harvestTime: 'Freshly Dug Yesterday',
    description: 'Aromatic fibreless raw ginger root grown organically in Wayanad soil.',
  },
  {
    id: 'PROD-110',
    name: 'Sweet Pumpkin (Mathanga)',
    hindiName: 'Kaddu',
    category: 'Gourds & Squashes',
    price: 30,
    unit: '1 kg Cut Piece',
    quantity: 25,
    seller: 'Lakshmi Amma (Bio Valley Organic)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-2',
    region: 'Palakkad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1570586437263-ab629fccc818?w=500&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewsCount: 16,
    harvestTime: 'Harvested 2 Days Ago',
    description: 'Bright orange sweet pumpkin packed with Beta Carotene and natural sweetness.',
  },
  {
    id: 'PROD-111',
    name: 'Ash Gourd (Kumbalanga)',
    hindiName: 'Petha',
    category: 'Gourds & Squashes',
    price: 28,
    unit: '1 kg',
    quantity: 30,
    seller: 'Lakshmi Amma (Bio Valley Organic)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-2',
    region: 'Palakkad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1598170845058-12ef4a4575c1?w=500&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewsCount: 12,
    harvestTime: 'Harvested Yesterday',
    description: 'Cooling organic winter melon ideal for detox juices and traditional Moru Curry.',
  },
  {
    id: 'PROD-112',
    name: 'Bottle Gourd (Lauki / Surakai)',
    hindiName: 'Lauki',
    category: 'Gourds & Squashes',
    price: 35,
    unit: '1 Piece (800g)',
    quantity: 20,
    seller: 'Ramesh Kumar (Green Canopy Farms)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-1',
    region: 'Wayanad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1590005176489-db2e714711fc?w=500&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewsCount: 9,
    harvestTime: 'Harvested Today Morning',
    description: 'Tender juicy bottle gourd grown naturally without synthetic growth hormones.',
  },
  {
    id: 'PROD-113',
    name: 'Yardlong Snake Gourd (Padavalanga)',
    hindiName: 'Chachinda',
    category: 'Gourds & Squashes',
    price: 40,
    unit: '500 g',
    quantity: 22,
    seller: 'Ananya Nair (Terrace Green Garden)',
    sellerRole: 'Home Garden Seller',
    sellerId: 'USR-HOME-1',
    region: 'Kozhikode',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=500&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 15,
    harvestTime: 'Harvested Today Morning',
    description: 'Crisp home-grown long snake gourds perfect for coconut thoran.',
  },
  {
    id: 'PROD-114',
    name: 'Ridge Gourd (Peechinga)',
    hindiName: 'Turai',
    category: 'Gourds & Squashes',
    price: 45,
    unit: '500 g',
    quantity: 28,
    seller: 'Ananya Nair (Terrace Green Garden)',
    sellerRole: 'Home Garden Seller',
    sellerId: 'USR-HOME-1',
    region: 'Kozhikode',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1590005176489-db2e714711fc?w=500&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewsCount: 19,
    harvestTime: 'Harvested Today at 6:30 AM',
    description: 'Fresh ridge gourds harvested from backyard trellis system.',
  },
  {
    id: 'PROD-115',
    name: 'Palakkad Bio Beetroot',
    hindiName: 'Chukandar',
    category: 'Root Vegetables',
    price: 50,
    unit: '500 g',
    quantity: 45,
    seller: 'Lakshmi Amma (Bio Valley Organic)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-2',
    region: 'Palakkad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1593105544559-ecb03bf76f82?w=500&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 31,
    harvestTime: 'Harvested Yesterday',
    description: 'Deep purple organic beetroots loaded with nitrates and antioxidants.',
  },
  {
    id: 'PROD-116',
    name: 'Nilgiri Crisp Carrots',
    hindiName: 'Gajar',
    category: 'Root Vegetables',
    price: 58,
    unit: '500 g',
    quantity: 50,
    seller: 'Ramesh Kumar (Green Canopy Farms)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-1',
    region: 'Wayanad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1598170845058-12ef4a4575c1?w=500&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 41,
    harvestTime: 'Harvested Yesterday',
    description: 'Sweet and crunchy orange carrots from mountain altitude farms.',
    isPopular: true,
  },
  {
    id: 'PROD-117',
    name: 'Raw Green Plantain (Nendran Kaya)',
    hindiName: 'Kacha Kela',
    category: 'Exotic & Special',
    price: 48,
    unit: '1 kg',
    quantity: 60,
    seller: 'Lakshmi Amma (Bio Valley Organic)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-2',
    region: 'Palakkad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1528825871115-3581a5387919?w=500&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 38,
    harvestTime: 'Harvested Today Morning',
    description: 'Unripe Nendran raw banana essential for traditional upperi and chips.',
  },
  {
    id: 'PROD-118',
    name: 'Organic Purple Brinjal (Vazhuthananga)',
    hindiName: 'Baingan',
    category: 'Root Vegetables',
    price: 36,
    unit: '500 g',
    quantity: 35,
    seller: 'Lakshmi Amma (Bio Valley Organic)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-2',
    region: 'Palakkad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=500&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewsCount: 20,
    harvestTime: 'Harvested Today',
    description: 'Shiny purple eggplants with soft seeds and tender skin.',
  },
  {
    id: 'PROD-119',
    name: 'Fresh Coriander Bunch (Malli Ela)',
    hindiName: 'Dhania',
    category: 'Spices & Herbs',
    price: 20,
    unit: '1 Bunch (150g)',
    quantity: 70,
    seller: 'Ananya Nair (Terrace Green Garden)',
    sellerRole: 'Home Garden Seller',
    sellerId: 'USR-HOME-1',
    region: 'Kozhikode',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1588879460618-9249e7d947d1?w=500&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 42,
    harvestTime: 'Harvested Today 6:00 AM',
    description: 'Aromatic cilantro leaves grown in rich compost beds.',
  },
  {
    id: 'PROD-120',
    name: 'Terrace Grown Fresh Mint (Pudina)',
    hindiName: 'Pudina',
    category: 'Spices & Herbs',
    price: 18,
    unit: '1 Bunch (100g)',
    quantity: 60,
    seller: 'Ananya Nair (Terrace Green Garden)',
    sellerRole: 'Home Garden Seller',
    sellerId: 'USR-HOME-1',
    region: 'Kozhikode',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=500&auto=format&fit=crop&q=80',
    rating: 5.0,
    reviewsCount: 29,
    harvestTime: 'Harvested 3 Hours Ago',
    description: 'Invigorating fresh mint leaves for herbal tea, chutneys, and juices.',
  },
  {
    id: 'PROD-121',
    name: 'Red Amaranthus Greens (Chuvanna Cheera)',
    hindiName: 'Lal Saag',
    category: 'Leafy Greens',
    price: 28,
    unit: '1 Bunch (350g)',
    quantity: 35,
    seller: 'Ramesh Kumar (Green Canopy Farms)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-1',
    region: 'Wayanad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 25,
    harvestTime: 'Harvested Today Morning',
    description: 'Vibrant red amaranth leaves bursting with iron and calcium.',
  },
  {
    id: 'PROD-122',
    name: 'Elephant Foot Yam (Chena)',
    hindiName: 'Suran',
    category: 'Root Vegetables',
    price: 65,
    unit: '1 kg Cut Piece',
    quantity: 40,
    seller: 'Lakshmi Amma (Bio Valley Organic)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-2',
    region: 'Palakkad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1593105544559-ecb03bf76f82?w=500&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewsCount: 19,
    harvestTime: 'Harvested 2 Days Ago',
    description: 'Aged non-itchy organic Yam root ideal for Olan, Erissery and stir fry.',
  },
  {
    id: 'PROD-123',
    name: 'Colocasia Taro Root (Chembu)',
    hindiName: 'Arbi',
    category: 'Root Vegetables',
    price: 52,
    unit: '500 g',
    quantity: 30,
    seller: 'Ramesh Kumar (Green Canopy Farms)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-1',
    region: 'Wayanad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1593105544559-ecb03bf76f82?w=500&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewsCount: 11,
    harvestTime: 'Freshly Dug Yesterday',
    description: 'Organic starchy taro tubers cultivated in Wayanad valley soil.',
  },
  {
    id: 'PROD-124',
    name: 'Raw Turmeric Rhizome (Manjal)',
    hindiName: 'Kacchi Haldi',
    category: 'Spices & Herbs',
    price: 45,
    unit: '250 g',
    quantity: 40,
    seller: 'Ramesh Kumar (Green Canopy Farms)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-1',
    region: 'Wayanad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=500&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 33,
    harvestTime: 'Fresh Harvest',
    description: 'High curcumin content fresh organic turmeric root for golden milk and curries.',
  },
  {
    id: 'PROD-125',
    name: 'Organic Sweet Potatoes (Madhura Kizhangu)',
    hindiName: 'Shakarkandi',
    category: 'Root Vegetables',
    price: 45,
    unit: '1 kg',
    quantity: 50,
    seller: 'Lakshmi Amma (Bio Valley Organic)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-2',
    region: 'Palakkad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 27,
    harvestTime: 'Harvested 2 Days Ago',
    description: 'Naturally sweet red-skinned root tubers grown without artificial fertilizers.',
  },
  {
    id: 'PROD-126',
    name: 'Fresh Lemons (Cherunarakam)',
    hindiName: 'Nimbu',
    category: 'Exotic & Special',
    price: 30,
    unit: '4 Pieces',
    quantity: 80,
    seller: 'Ananya Nair (Terrace Green Garden)',
    sellerRole: 'Home Garden Seller',
    sellerId: 'USR-HOME-1',
    region: 'Kozhikode',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1534531141161-e4ecc3e8749a?w=500&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 37,
    harvestTime: 'Harvested Today Morning',
    description: 'Juicy yellow country lemons plucked fresh from home garden tree.',
  },
  {
    id: 'PROD-127',
    name: 'White Radish (Mullangi)',
    hindiName: 'Mooli',
    category: 'Root Vegetables',
    price: 35,
    unit: '500 g',
    quantity: 30,
    seller: 'Ramesh Kumar (Green Canopy Farms)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-1',
    region: 'Wayanad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1598170845058-12ef4a4575c1?w=500&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewsCount: 14,
    harvestTime: 'Harvested Yesterday',
    description: 'Pungent crisp white radishes with fresh edible green tops.',
  },
  {
    id: 'PROD-128',
    name: 'Fresh Button Mushrooms (Koon)',
    hindiName: 'Kukurmutta',
    category: 'Exotic & Special',
    price: 65,
    unit: '200 g Pack',
    quantity: 25,
    seller: 'Ananya Nair (Terrace Green Garden)',
    sellerRole: 'Home Garden Seller',
    sellerId: 'USR-HOME-1',
    region: 'Kozhikode',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=500&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 30,
    harvestTime: 'Harvested Today 5:00 AM',
    description: 'Clean white oyster button mushrooms cultivated organically indoors.',
  },
  {
    id: 'PROD-129',
    name: 'Raw Sour Mango (Pacha Manga)',
    hindiName: 'Kacha Aam',
    category: 'Exotic & Special',
    price: 40,
    unit: '500 g',
    quantity: 40,
    seller: 'Lakshmi Amma (Bio Valley Organic)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-2',
    region: 'Palakkad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=500&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 22,
    harvestTime: 'Harvested Today Morning',
    description: 'Tangy green mangoes ideal for fish curry and homemade pickle.',
  },
  {
    id: 'PROD-130',
    name: 'Organic Country Garlic (Veluthulli)',
    hindiName: 'Lahsun',
    category: 'Spices & Herbs',
    price: 85,
    unit: '250 g',
    quantity: 60,
    seller: 'Ramesh Kumar (Green Canopy Farms)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-1',
    region: 'Wayanad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?w=500&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 48,
    harvestTime: 'Cured & Sun Dried',
    description: 'Small clove hill garlic packed with intense pungency and medicinal properties.',
  },
  {
    id: 'PROD-131',
    name: 'Fresh Fenugreek Leaves (Uluva Ela / Methi)',
    hindiName: 'Methi',
    category: 'Leafy Greens',
    price: 25,
    unit: '1 Bunch (200g)',
    quantity: 35,
    seller: 'Ananya Nair (Terrace Green Garden)',
    sellerRole: 'Home Garden Seller',
    sellerId: 'USR-HOME-1',
    region: 'Kozhikode',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewsCount: 17,
    harvestTime: 'Harvested Today Morning',
    description: 'Fresh micro fenugreek greens grown in organic tray setups.',
  },
  {
    id: 'PROD-132',
    name: 'Organic Tender Coconut (Karikku)',
    hindiName: 'Nariyal',
    category: 'Exotic & Special',
    price: 45,
    unit: '1 Nut',
    quantity: 50,
    seller: 'Lakshmi Amma (Bio Valley Organic)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-2',
    region: 'Palakkad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1543362906-acfc16c67564?w=500&auto=format&fit=crop&q=80',
    rating: 5.0,
    reviewsCount: 60,
    harvestTime: 'Plucked Today at 7:00 AM',
    description: 'Sweet electrolyte-rich tender coconut water with soft cream meat.',
    isPopular: true,
  },
  {
    id: 'PROD-133',
    name: 'Bio-Farm Onions (Savanala Ulli)',
    hindiName: 'Pyaz',
    category: 'Root Vegetables',
    price: 36,
    unit: '1 kg',
    quantity: 90,
    seller: 'Lakshmi Amma (Bio Valley Organic)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-2',
    region: 'Palakkad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cf?w=500&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewsCount: 52,
    harvestTime: 'Cured 3 Days Ago',
    description: 'Medium size organic red onions with high dry matter and shelf life.',
  },
  {
    id: 'PROD-134',
    name: 'Wayanad Hill Potatoes (Urulakkizhangu)',
    hindiName: 'Aloo',
    category: 'Root Vegetables',
    price: 34,
    unit: '1 kg',
    quantity: 100,
    seller: 'Ramesh Kumar (Green Canopy Farms)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-1',
    region: 'Wayanad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 64,
    harvestTime: 'Harvested 3 Days Ago',
    description: 'Firm soil-covered mountain potatoes ideal for boiling and mashing.',
  },
  {
    id: 'PROD-135',
    name: 'Cluster Beans (Kothavarakka)',
    hindiName: 'Gwar Phali',
    category: 'Pods & Beans',
    price: 38,
    unit: '500 g',
    quantity: 25,
    seller: 'Lakshmi Amma (Bio Valley Organic)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-2',
    region: 'Palakkad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1628773822503-930a8581898e?w=500&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewsCount: 13,
    harvestTime: 'Harvested Today Morning',
    description: 'Nutritious tender cluster beans grown organically without chemical weedicides.',
  },
  {
    id: 'PROD-136',
    name: 'Broad Beans (Avarakka)',
    hindiName: 'Sem Phali',
    category: 'Pods & Beans',
    price: 42,
    unit: '500 g',
    quantity: 30,
    seller: 'Ananya Nair (Terrace Green Garden)',
    sellerRole: 'Home Garden Seller',
    sellerId: 'USR-HOME-1',
    region: 'Kozhikode',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1628773822503-930a8581898e?w=500&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 18,
    harvestTime: 'Harvested Today 6:00 AM',
    description: 'Flat broad beans harvested at early pod stage for sweet tender seeds.',
  },
  {
    id: 'PROD-137',
    name: 'Malabar Spinach (Valli Cheera)',
    hindiName: 'Poi Saag',
    category: 'Leafy Greens',
    price: 30,
    unit: '1 Bunch (400g)',
    quantity: 20,
    seller: 'Ananya Nair (Terrace Green Garden)',
    sellerRole: 'Home Garden Seller',
    sellerId: 'USR-HOME-1',
    region: 'Kozhikode',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 21,
    harvestTime: 'Harvested Today Morning',
    description: 'Fleshy succulent vine spinach ideal for lentil curries.',
  },
  {
    id: 'PROD-138',
    name: 'Organic Green Peas (Pachappattani)',
    hindiName: 'Matar',
    category: 'Pods & Beans',
    price: 70,
    unit: '500 g Unshelled',
    quantity: 35,
    seller: 'Ramesh Kumar (Green Canopy Farms)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-1',
    region: 'Wayanad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1587735243615-c03f25aaff15?w=500&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 36,
    harvestTime: 'Harvested Yesterday',
    description: 'Plump sweet green peas pods cultivated in Wayanad hills.',
  },
  {
    id: 'PROD-139',
    name: 'Bird Eye Chilli (Kanthari Mulaku)',
    hindiName: 'Kanthari',
    category: 'Spices & Herbs',
    price: 90,
    unit: '100 g Pack',
    quantity: 25,
    seller: 'Ananya Nair (Terrace Green Garden)',
    sellerRole: 'Home Garden Seller',
    sellerId: 'USR-HOME-1',
    region: 'Kozhikode',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1588880331179-bc9b93a8cb5e?w=500&auto=format&fit=crop&q=80',
    rating: 5.0,
    reviewsCount: 41,
    harvestTime: 'Harvested Today Morning',
    description: 'Pungent white indigenous kanthari chillies prized for medicinal value and chammanthi.',
    isPopular: true,
  },
  {
    id: 'PROD-140',
    name: 'Organic Tapioca (Kappa)',
    hindiName: 'Tapioca',
    category: 'Root Vegetables',
    price: 35,
    unit: '1 kg',
    quantity: 70,
    seller: 'Lakshmi Amma (Bio Valley Organic)',
    sellerRole: 'Farmer',
    sellerId: 'USR-FARM-2',
    region: 'Palakkad',
    organicVerified: true,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 50,
    harvestTime: 'Uprooted Today Morning',
    description: 'Fresh white tapioca roots that boil soft in minutes. Kerala traditional staple.',
    isPopular: true,
  },
];

export const INITIAL_ORDERS = [
  {
    id: 'ORD-8091',
    customerId: 'USR-CUST-1',
    customerName: 'Akash K. Shankar',
    customerPhone: '+91 98470 12345',
    address: {
      street: 'Flat 4B, Malabar Heights, Beach Road',
      city: 'Kozhikode',
      region: 'Kozhikode',
      pincode: '673001',
      deliveryNotes: 'Please ring the bell and leave near door step.',
    },
    items: [
      {
        productId: 'PROD-101',
        productName: 'Organic Country Tomatoes (Thakkali)',
        price: 48,
        unit: '1 kg',
        quantity: 1,
        seller: 'Ramesh Kumar (Green Canopy Farms)',
        sellerId: 'USR-FARM-1',
        image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&auto=format&fit=crop&q=80',
      },
      {
        productId: 'PROD-102',
        productName: 'Fresh Organic Palak Spinach (Cheera)',
        price: 32,
        unit: '1 Bunch (300g)',
        quantity: 2,
        seller: 'Ananya Nair (Terrace Green Garden)',
        sellerId: 'USR-HOME-1',
        image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500&auto=format&fit=crop&q=80',
      },
      {
        productId: 'PROD-105',
        productName: 'Organic Small Shallots (Cheriya Ulli)',
        price: 75,
        unit: '500 g',
        quantity: 1,
        seller: 'Lakshmi Amma (Bio Valley Organic)',
        sellerId: 'USR-FARM-2',
        image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cf?w=500&auto=format&fit=crop&q=80',
      },
    ],
    subtotal: 187,
    deliveryFee: 30,
    discount: 20,
    totalAmount: 197,
    paymentMethod: 'UPI' as const,
    paymentStatus: 'Paid' as const,
    status: 'Out for Delivery' as const,
    outletId: 'USR-OUTLET-1',
    outletName: 'Kozhikode Central Community Outlet',
    assignedDeliveryPartnerId: 'USR-DELIV-1',
    assignedDeliveryPartnerName: 'Rajesh V. (Eco Delivery Express)',
    assignedDeliveryPartnerPhone: '+91 97455 66778',
    invoiceNumber: 'INV-2026-001',
    createdAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    timeline: [
      { status: 'Pending' as const, timestamp: new Date(Date.now() - 3600000 * 3).toISOString(), note: 'Order placed by Akash K. Shankar', updatedBy: 'Akash K. Shankar' },
      { status: 'Outlet Accepted' as const, timestamp: new Date(Date.now() - 3600000 * 2.5).toISOString(), note: 'Order accepted at Kozhikode Outlet', updatedBy: 'Outlet Manager' },
      { status: 'Packing' as const, timestamp: new Date(Date.now() - 3600000 * 2).toISOString(), note: 'Organic Produce packed in eco-bag', updatedBy: 'Outlet Manager' },
      { status: 'Ready' as const, timestamp: new Date(Date.now() - 3600000 * 1.5).toISOString(), note: 'Ready for delivery dispatch', updatedBy: 'Outlet Manager' },
      { status: 'Assigned' as const, timestamp: new Date(Date.now() - 3600000 * 1.2).toISOString(), note: 'Assigned to Rajesh V.', updatedBy: 'Outlet Manager' },
      { status: 'Out for Delivery' as const, timestamp: new Date(Date.now() - 3600000 * 0.8).toISOString(), note: 'Partner is on the way with eco-bike', updatedBy: 'Rajesh V.' },
    ],
  },
  {
    id: 'ORD-8092',
    customerId: 'USR-CUST-1',
    customerName: 'Akash K. Shankar',
    customerPhone: '+91 98470 12345',
    address: {
      street: 'Flat 4B, Malabar Heights, Beach Road',
      city: 'Kozhikode',
      region: 'Kozhikode',
      pincode: '673001',
    },
    items: [
      {
        productId: 'PROD-140',
        productName: 'Organic Tapioca (Kappa)',
        price: 35,
        unit: '1 kg',
        quantity: 2,
        seller: 'Lakshmi Amma (Bio Valley Organic)',
        sellerId: 'USR-FARM-2',
        image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80',
      },
      {
        productId: 'PROD-139',
        productName: 'Bird Eye Chilli (Kanthari Mulaku)',
        price: 90,
        unit: '100 g Pack',
        quantity: 1,
        seller: 'Ananya Nair (Terrace Green Garden)',
        sellerId: 'USR-HOME-1',
        image: 'https://images.unsplash.com/photo-1588880331179-bc9b93a8cb5e?w=500&auto=format&fit=crop&q=80',
      },
    ],
    subtotal: 160,
    deliveryFee: 30,
    discount: 0,
    totalAmount: 190,
    paymentMethod: 'COD' as const,
    paymentStatus: 'Pending COD' as const,
    status: 'Outlet Accepted' as const,
    outletId: 'USR-OUTLET-1',
    outletName: 'Kozhikode Central Community Outlet',
    invoiceNumber: 'INV-2026-002',
    createdAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 0.8).toISOString(),
    timeline: [
      { status: 'Pending' as const, timestamp: new Date(Date.now() - 3600000 * 1).toISOString(), note: 'Order placed via Cash on Delivery', updatedBy: 'Akash K. Shankar' },
      { status: 'Outlet Accepted' as const, timestamp: new Date(Date.now() - 3600000 * 0.8).toISOString(), note: 'Accepted by Outlet Manager', updatedBy: 'Outlet Manager' },
    ],
  },
  {
    id: 'ORD-8088',
    customerId: 'USR-CUST-1',
    customerName: 'Akash K. Shankar',
    customerPhone: '+91 98470 12345',
    address: {
      street: 'Flat 4B, Malabar Heights, Beach Road',
      city: 'Kozhikode',
      region: 'Kozhikode',
      pincode: '673001',
    },
    items: [
      {
        productId: 'PROD-116',
        productName: 'Nilgiri Crisp Carrots',
        price: 58,
        unit: '500 g',
        quantity: 2,
        seller: 'Ramesh Kumar (Green Canopy Farms)',
        sellerId: 'USR-FARM-1',
        image: 'https://images.unsplash.com/photo-1598170845058-12ef4a4575c1?w=500&auto=format&fit=crop&q=80',
      },
      {
        productId: 'PROD-132',
        productName: 'Organic Tender Coconut (Karikku)',
        price: 45,
        unit: '1 Nut',
        quantity: 2,
        seller: 'Lakshmi Amma (Bio Valley Organic)',
        sellerId: 'USR-FARM-2',
        image: 'https://images.unsplash.com/photo-1543362906-acfc16c67564?w=500&auto=format&fit=crop&q=80',
      },
    ],
    subtotal: 206,
    deliveryFee: 30,
    discount: 50,
    totalAmount: 186,
    paymentMethod: 'WALLET' as const,
    paymentStatus: 'Paid' as const,
    status: 'Delivered' as const,
    outletId: 'USR-OUTLET-1',
    outletName: 'Kozhikode Central Community Outlet',
    assignedDeliveryPartnerId: 'USR-DELIV-1',
    assignedDeliveryPartnerName: 'Rajesh V. (Eco Delivery Express)',
    invoiceNumber: 'INV-2026-000',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1.8).toISOString(),
    timeline: [
      { status: 'Pending' as const, timestamp: new Date(Date.now() - 86400000 * 2).toISOString(), note: 'Order placed', updatedBy: 'Akash K. Shankar' },
      { status: 'Outlet Accepted' as const, timestamp: new Date(Date.now() - 86400000 * 1.95).toISOString(), note: 'Accepted', updatedBy: 'Outlet Manager' },
      { status: 'Packing' as const, timestamp: new Date(Date.now() - 86400000 * 1.9).toISOString(), note: 'Packed', updatedBy: 'Outlet Manager' },
      { status: 'Ready' as const, timestamp: new Date(Date.now() - 86400000 * 1.88).toISOString(), note: 'Ready', updatedBy: 'Outlet Manager' },
      { status: 'Assigned' as const, timestamp: new Date(Date.now() - 86400000 * 1.86).toISOString(), note: 'Assigned', updatedBy: 'Outlet Manager' },
      { status: 'Out for Delivery' as const, timestamp: new Date(Date.now() - 86400000 * 1.83).toISOString(), note: 'Out for delivery', updatedBy: 'Rajesh V.' },
      { status: 'Delivered' as const, timestamp: new Date(Date.now() - 86400000 * 1.8).toISOString(), note: 'Delivered to customer', updatedBy: 'Rajesh V.' },
    ],
  },
];

export const INITIAL_COMMUNITY_POSTS = [
  {
    id: 'POST-1',
    authorName: 'Ananya Nair',
    authorRole: 'Home Garden Seller' as const,
    authorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    title: '🌿 How I grown 15kg Organic Palak on my 200 sq.ft Terrace Garden!',
    content: 'Friends, here is my secret formula for rich green spinach on apartment terraces: Use 40% vermicompost, 40% coco peat, and 20% garden soil. Spray diluted buttermilk once a week to protect against leaf spot pests. No chemicals needed!',
    category: 'Gardening Tips' as const,
    tags: ['TerraceGarden', 'OrganicPalak'],
    likes: 42,
    likedByCurrentUser: false,
    comments: [
      { id: 'C1', authorName: 'Ramesh Kumar', authorRole: 'Farmer' as const, text: 'Excellent advice Ananya! Buttermilk spray works like magic in hill regions too.', timestamp: '2 hours ago' },
      { id: 'C2', authorName: 'Akash K. Shankar', authorRole: 'Customer' as const, text: 'Ordered your palak yesterday! Freshness was unbelievable.', timestamp: '1 hour ago' },
    ],
    timestamp: 'Yesterday at 4:30 PM',
    imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'POST-2',
    authorName: 'Ramesh Kumar',
    authorRole: 'Farmer' as const,
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    title: '🌾 Transitioning from conventional farming to Natural Farming (ZNFBN)',
    content: 'Four years ago, my Wayanad soil was depleted due to chemical pesticides. By shifting to Jeevamrutha manure and mulching, soil earthworms came back! Today my tomato yield is 20% higher and 100% organic verified.',
    category: 'Organic Farming' as const,
    tags: ['Wayanad', 'NaturalFarming'],
    likes: 89,
    likedByCurrentUser: true,
    comments: [
      { id: 'C3', authorName: 'Lakshmi Amma', authorRole: 'Farmer' as const, text: 'Inspirational work Ramesh! Palakkad farmers are following suit.', timestamp: '5 hours ago' },
    ],
    timestamp: '2 days ago',
    imageUrl: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=600&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'NOTIF-1',
    targetRole: 'Customer' as const,
    title: '🚚 Order Out for Delivery!',
    message: 'Your order ORD-8091 is out for delivery with Rajesh V. (Eco Delivery).',
    orderId: 'ORD-8091',
    timestamp: '30 mins ago',
    read: false,
    type: 'ORDER' as const,
  },
  {
    id: 'NOTIF-2',
    targetRole: 'Outlet Manager' as const,
    title: '📦 New Order Received!',
    message: 'New Cash on Delivery order ORD-8092 received for Kozhikode Outlet.',
    orderId: 'ORD-8092',
    timestamp: '45 mins ago',
    read: false,
    type: 'ORDER' as const,
  },
  {
    id: 'NOTIF-3',
    targetRole: 'ALL' as const,
    title: '🌱 Fresh Harvest Alert!',
    message: 'Over 15 fresh organic hill vegetables just arrived at Kozhikode Outlet.',
    timestamp: '2 hours ago',
    read: true,
    type: 'PROMO' as const,
  },
];

export const INITIAL_COMPLAINTS = [
  {
    id: 'CMP-101',
    userId: 'USR-CUST-1',
    userName: 'Akash K. Shankar',
    userRole: 'Customer' as const,
    orderId: 'ORD-8088',
    subject: 'Delayed delivery by 20 minutes',
    description: 'Delivery reached at 7:20 PM instead of promised 7:00 PM slot due to heavy rain in Kozhikode Beach Road.',
    status: 'Resolved' as const,
    priority: 'Low' as const,
    timestamp: 'Yesterday',
  },
];

export const INITIAL_REVIEWS = [
  {
    id: 'REV-1',
    productId: 'PROD-101',
    productName: 'Organic Country Tomatoes (Thakkali)',
    orderId: 'ORD-8088',
    customerName: 'Akash K. Shankar',
    rating: 5,
    comment: 'Super fresh country tomatoes! True sour tomato taste that you never get in supermarkets.',
    timestamp: 'Yesterday',
  },
  {
    id: 'REV-2',
    productId: 'PROD-116',
    productName: 'Nilgiri Crisp Carrots',
    orderId: 'ORD-8088',
    customerName: 'Akash K. Shankar',
    rating: 5,
    comment: 'Crispy, sweet and clean. Highly recommended!',
    timestamp: '2 days ago',
  },
];

export const INITIAL_DELIVERIES = [
  {
    id: 'DEL-1',
    orderId: 'ORD-8091',
    customerName: 'Akash K. Shankar',
    customerPhone: '+91 98470 12345',
    address: 'Flat 4B, Malabar Heights, Beach Road, Kozhikode - 673001',
    region: 'Kozhikode',
    itemsCount: 3,
    totalAmount: 197,
    paymentMethod: 'UPI (Paid)',
    codAmountToCollect: 0,
    status: 'Out for Delivery' as const,
    outletName: 'Kozhikode Central Community Outlet',
    assignedPartnerId: 'USR-DELIV-1',
    assignedPartnerName: 'Rajesh V. (Eco Delivery Express)',
    estimatedDeliveryTime: '20 Mins',
  },
];

export function getInitialDatabaseState(): DatabaseState {
  return {
    users: INITIAL_USERS,
    products: INITIAL_PRODUCTS,
    orders: INITIAL_ORDERS,
    deliveries: INITIAL_DELIVERIES,
    payments: [
      {
        id: 'PAY-1',
        orderId: 'ORD-8091',
        customerName: 'Akash K. Shankar',
        amount: 197,
        method: 'UPI',
        status: 'SUCCESS',
        transactionRef: 'UPI/2026/88210923',
        timestamp: new Date(Date.now() - 3600000 * 3).toISOString(),
      },
    ],
    notifications: INITIAL_NOTIFICATIONS,
    reviews: INITIAL_REVIEWS,
    complaints: INITIAL_COMPLAINTS,
    communityPosts: INITIAL_COMMUNITY_POSTS,
    subscriptionPlans: INITIAL_SUBSCRIPTION_BOXES,
    userSubscriptions: [],
    coupons: INITIAL_COUPONS,
    lastUpdated: new Date().toISOString(),
  };
}
